name: Release Tag Workflow - macOS
description: Build and package a Swift project for release -- macOS.

inputs:
  work_dir:
    required: false
    default: "."
    description: Release working dirctory

jobs:
  build-and-upload:
    name: macOS-Release
    strategy:
      matrix:
        include:
          - macos-version: macos-14
            xcode-version: latest-stable
          - macos-version: macos-15
            xcode-version: latest-stable
    runs-on: ${{ matrix.macos-version }}

    steps:
      - name: Select appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
          
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Download shared CI release script
        uses: actions/checkout@v4
        working-dirctory: ${{ inputs.work_dir }}
        with: 
          repository: SJJC-Team/ci
          path: .ci
          
      - name: Make release script executable
        working-dirctory: ${{ inputs.work_dir }}
        run: |
          cp .ci/.github/actions/release-macos/release.sh ./release.sh
          chmod +x ./release.sh

      - name: Build and package manager
        working-directory: ${{ inputs.work_dir }}
        run: |
          ./release.sh xcode-${{ matrix.xcode-version }}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        working-dirctory: ${{ inputs.work_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.CLWANG_RELEASE_ACCESS }}
        with:
          files: |
            release/*.tar.gz
