name: Release Tag Workflow - Ubuntu
description: Build and package a Swift project for release -- Ubuntu.

inputs:
  work_dir:
    required: false
    default: "."
    description: Release working dirctory


jobs:
  build-and-upload:
    name: Ubuntu-Release
    runs-on: ${{ matrix.os }}
    container: swift:${{ matrix.swift_version }}

    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        swift_version: ["6.0", "6.1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download shared CI release script
        uses: actions/checkout@v4
        working-dirctory: ${{ inputs.work_dir }}
        with:
          repository: SJJC-Team/ci
          path: .ci
          
      - name: Make release script executable
        working-dirctory: ${{ inputs.work_dir }}
        run: |
          cp .ci/.github/actions/release-ubuntu/release.sh ./release.sh
          chmod +x ./release.sh

      - name: Build and package App
        working-dirctory: ${{ inputs.work_dir }}
        run: |
          ./release.sh swift-${{ matrix.swift_version }}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        working-dirctory: ${{ inputs.work_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.CLWANG_RELEASE_ACCESS }}
        with:
          files: |
            release/*.tar.gz
