name: Unit Test
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ develop ] }

jobs:
  unit-tests:
    uses: whooshing-workshop/ci/.github/workflows/run-unit-tests.yml@develop
    with:
      work_dir: "./ci-testing"

      with_api_check: false
      with_tsan: true
      with_release_mode_testing: true
      ios_xcodebuild_action: ''

      with_musl: true
      extra_musl_flags: --target ci-testing

      only_build: false
      with_pg_version: 17
      with_pg_configs: |
        testing testing 123456 5432 testing2
        user1 db1 pass1 5433

      with_eopa_host: "localhost"
      with_eopa_port: 8282
      with_eopa_version: v1.13.1
    secrets: inherit
